version: "3.7"

services:
  mariadb:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    working_dir: /home/frappe
    volumes:
      - ./init.sh:/workspace/init.sh
      - frappe-lms-bench:/home/frappe/frappe-lms-bench
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

volumes:
  mariadb-data:
  frappe-lms-bench:
